import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "@/Providers";
import PhrasalVerbsProvider from "./context/PhrasalVerbsProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Phrasal Verbs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
        <PhrasalVerbsProvider>
          <Navbar />
          <div>
            <div className="max-w-[1280px] mx-auto px-4">
              {children}
            </div>
          </div>
        </PhrasalVerbsProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
